Use Preact for wikipedia.de banner (#249)
Updated dependencies for Babel 7
Added jsx plugin
Change shared banner modules to ES modules

Babel 7 and the `useBuiltIns: 'usage'` setting injects ES6 imports into
the CommonJS-based banners. This leads to the error message
TypeError: "exports" is read-only` in the compiled banners (See also
https://github.com/webpack/webpack/issues/3997 and
https://github.com/babel/babel/issues/6980 ).

Changed `getSkin` in "BannerFunctions" to preload all skin
manipulating classes.

Add Preact desktop banner

Pass the callback to the child method up the component hierarchy, via a
"trigger method", so the mobile banner can call the method for the
animation when it shows the fullpage banner.

Add explicitly evaluated spaces to TextHighlight child text to
circumvent [JSX space-eating behavior][1].

[1]: https://github.com/facebook/react/issues/4134